Neos:
  Neos:
    modules:
      management:
        submodules:
          partialcontentmodule:
            label: 'Partial Content Import/Export'
            controller: '\Networkteam\PartialContentModule\Controller\ModuleController'
            description: 'Networkteam.PartialContentModule:Modules:module.description'
            icon: 'fas fa-exchange-alt'
            privilegeTarget: 'Networkteam.PartialContentModule:Module'
