Neos:
  Neos:
    modules:
      management:
        submodules:
          partialcontentmodule:
            label: 'Networkteam.PartialContentModule:Modules:importExport.label'
            description: 'Networkteam.PartialContentModule:Modules:importExport.description'
            controller: 'Networkteam\PartialContentModule\Controller\ModuleController'
            icon: fas fa-exchange-alt
            mainStylesheet: 'Main'
            privilegeTarget: 'Networkteam.PartialContentModule:Module'

    userInterface:
      translation:
        autoInclude:
          'Networkteam.PartialContentModule':
            - Modules